# Generated by Django 5.1.1 on 2024-09-04 04:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_groups_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='invite_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='invite_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
